<?php

namespace Database\Seeders;

use App\Models\InventoryShipment;
use App\Models\User;
use Illuminate\Database\Seeder;

class InventoryShipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get first admin user
        $admin = User::role('admin')->first();

        if (!$admin) {
            $this->command->warn('No admin user found. Please create an admin user first.');
            return;
        }

        $shipments = [
            [
                'order' => 4181,
                'title' => 'Cast Iron Steak Grill Pan with Wooden Serving Tray Thick Griddle Plate',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => 'Received',
                'transporter' => 'Tamuka',
                'date' => null,
                'eta' => null,
                'f_status' => 'Received',
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4276,
                'title' => 'Manual Can Opener heavy duty construction tin Openers Stainless-Black',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => 'Not Yet',
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 3744,
                'title' => 'Supersonic Electric 5-Tray Food Dehydrator Biltong Maker 360AirCirculation',
                'quantity' => 1,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4263,
                'title' => 'Nicki Minaj Onika Body Mist 235ml Spray for her (Parallel import )',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 3961,
                'title' => 'Laser Plasma Pen Mole Removal Pens Dark Spot Remover',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 3980,
                'title' => 'Oase Filtral 6000 Pond Filter- Complete pump UV Filtration Fountain head',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 3986,
                'title' => 'Calvin Klein Obsession For Men 125ml',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4024,
                'title' => 'Peppa Pig Umbrella',
                'quantity' => 1,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4028,
                'title' => 'Hikvision 1080p 16 Channel Turbo HD kit with 2TB HDD DIY CCTV Kit',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4072,
                'title' => 'Creative Deco 50 Pack Velvet Hangers',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 3969,
                'title' => 'Scotsman Ice machine EC106/107 (50kg 24hours)',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40323,
                'title' => 'MAC AFRIC 100 Litre 2.2 KW (3 HP) 230 V Belt Driven V-Head Compressor',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40321,
                'title' => 'Konnwei KW680 OBD2 Automotive Scanner',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40320,
                'title' => 'MikroTik 8 Gigabit 1x2.5Gbps SFP Dual Core WiFi 6 Router - L009UiGS-2HaxD',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4122,
                'title' => 'Bamboo Serving Boat Plates x 50 - 90mm',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4124,
                'title' => '10m x 4.9m Solar Swimming Pool Blue Bubble Cover / Blanket',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4124,
                'title' => 'Layered Heart-Shaped Anklet in Yellow Gold',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4154,
                'title' => 'Beyblade BBX Xtreme Battle Set',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4176,
                'title' => 'Hisense 15 Place Dishwasher with LED Display - Silver',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6977,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4176,
                'title' => 'Samsung 15Kg AI Top Loader Washing Machine',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6977,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4171,
                'title' => '100M Blue Strip Light 220V',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4185,
                'title' => 'Goodtrip 205/60R16 92V Goodtrip GR-66',
                'quantity' => 4,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4245,
                'title' => 'FTS 15" Plastic Passive 250W Speaker [FTS-1515P]',
                'quantity' => 2,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4271,
                'title' => 'Aloe Vera Gel - 1 Litre',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4140,
                'title' => '2 pair Moisturizing Socks for Dry Cracked Feet,Heel Socks Gel Socks',
                'quantity' => 1,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4284,
                'title' => 'HP OfficeJet Pro 9120 All-in-One Printer',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6979,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4284,
                'title' => 'Money Counter with Counterfeit Detection & Extra Display',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40351,
                'title' => 'CRC Throttle Body & Air-Intake Cleaner 340 gram Aerosol',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4287,
                'title' => 'Russell Hobbs 6L 16 Multi Function Digital Pressure Cooker',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6979,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4287,
                'title' => 'Ultra-quiet Indoor Sports Exercise Spinning Fitness Bicycle',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6977,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4287,
                'title' => 'Reebok- Fitness A2.0 Treadmill - Black and Silver',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6977,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4285,
                'title' => 'Candle Wax Melting Pot Kit with 5 Stainless Steel Accessories included',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4285,
                'title' => 'Candle Wicks - Waxed & Tabbed - 15cm - 50 pieces - 1 Pack',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4285,
                'title' => '1kg Soy Wax for Candle Making',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40354,
                'title' => '5M VR Link Cable 16FT Oculus Quest2 Meta USB3 3A Fast Charge Type-C Headset',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4300,
                'title' => 'MB W204 Wiper Blades A2048201745 - Premium Replacement Set',
                'quantity' => 1,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4317,
                'title' => '2025 New R36MAX Retro Handheld Game Console with 64G Built-in 18000+ Games - Black',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4324,
                'title' => 'GetUp Cruze 150 Walking Pad Treadmill with Bluetooth Speakers',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6977,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4325,
                'title' => 'Replacement Ear-Pads Cushions for Bose QuietComfort QC-35 QC-25 QC-15',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4325,
                'title' => 'Wilson Profile JGI Junior Package Medium Golf Set - Age 8 to 11 years',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6979,
                'received_by' => null,
                'notes' => null,
            ],

            [
                'order' => 4337,
                'title' => '2 in 1 Baby High Chair Baby Feeding Chair -Baby Booster Chair - Pink',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40398,
                'title' => 'EcoFlow RIVER 3 Portable Power Station',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4337,
                'title' => 'Nonstick & Leak-Proof Cake Pan Set',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Kids Bicycle Training Wheels Bike with Steel Fork for Children\'s',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Pretty Baby Kids Bike - Pink',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Kids Bicycle Training Wheels Bike with Steel Fork for Children\'s',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Scooter with Suitcase for Kids with LED Lit Wheels - 2-in-1 - Purple (Size: 16 Inches)',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Scooter with Suitcase for Kids with LED Lit Wheels - 2-in-1 - Size: 16"',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Adjustable Strength Exercise Workout Dumbell Weight Bench with Foldable',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'HexPro Rubber-Coated Dumbbells - 20 kg',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => '40kg Dumbell Set',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Princess Dress Up & Jewelry Boutique, Girl Role Play Gifts Toddler Toys',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40411,
                'title' => 'MAC AFRIC 1/2" IN Female to 3/8" IN Male Socket Adapter',
                'quantity' => 1,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4321,
                'title' => 'Modern LED Pendant Lights Aluminum & Acrylic-6991.',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 3618,
                'title' => 'Sunshine P-3005D 5A 30V DC Power Supply With 3-Digital Display',
                'quantity' => 2,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4493,
                'title' => '100m Natural Jute Twine Burlap String Hemp Rope Wedding Gift Wrapping Cords',
                'quantity' => 1,
                'destination' => 'Mutare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'Motor Bike Cover Oxford Fabric All Weather Proof Waterproof Outdoor Storage - 2XL',
                'quantity' => 1,
                'destination' => 'Mutare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40254,
                'title' => 'Brother JV1400 Basic Sewing Machine',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40254,
                'title' => 'Hisense 85-inch QLED 4K TV-85Q6Q',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40322,
                'title' => 'Delonghi - Magnifica Plus Bean to Cup Coffee Machine - ECAM320.61.G',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40444,
                'title' => 'Outdoor Trolley Insulated/Cooler Box with Wheels 45L - Green',
                'quantity' => 9,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40444,
                'title' => 'Bos Outdoor Cooler Box 75L',
                'quantity' => 5,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40274,
                'title' => 'Parrot Products Full Motion Bracket 60" - 100" (VESA Compatible)',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40274,
                'title' => 'Samsung 98-inch Crystal UHD 4K-98DU9000',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6977,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40317,
                'title' => 'Apple iPad 11inch A16 Wi-Fi 128GB - Blue',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40196,
                'title' => 'Portable Electric Balloon Pump Inflator',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'Sleep Science - 9Kg - 152 x 203cm - Bamboo Weighted Blanket',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => '2.5Mpa Manual Pressure Test Pump 2.5Mpa Manual Pressure Test Pump',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'ndustrial 4 Plate Catering Gas Stove',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => '3Piece Wooden Wall Mounted Shelves Floating Shelves for Wall Bathroom Home',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'Genuine Leather Crossbody - Cellphone Sling Handbag - for Women| MIRELLE - Pecan Brown Genuine Leather Crossbody - Cellphone Sling Handbag - for Women| MIRELLE - Pecan Brown Qty: 1',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'Gym Keyring - Dumbbell',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'SOiL Organic Jojoba Oil 100ml',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'SOiL Organic Spearmint Essential Oil SOiL Organic Spearmint Essential Oil',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'SOiL Organic Rosehip Oil 100ml',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'GetUp Rubber Hex Dumbbell - Various Weights - 12.5 kg',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => null,
                'title' => 'Portable Electric Balloon Pump Inflator Portable Electric Balloon Pump Inflator Qty: 1',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40203,
                'title' => 'Anti White Hair Anti Hair Loss Spray Hair Colour Restoration Hair Growth',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40222,
                'title' => 'Size 126 Rubber Bands 100g Pack - Large Beige Elastic Bands (7.9" x 1/4")',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40223,
                'title' => 'RealEmpress Dark Knuckle Brightening Serum',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40224,
                'title' => 'Omni Gold Extra Brightening Anti-Marks Cream 2 pack',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40227,
                'title' => 'Automatic Hydraulic Door Closer Overhead Concealed Silent Slow Gate Closer',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40230,
                'title' => 'Urn 20LT Electric Stainless-Steel',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40231,
                'title' => 'Xiaomi Mi LCD 13.5" Writing Tablet - White',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => null,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 4032,
                'title' => 'Sunbeam Waffle Maker 750W - SWM-300',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40346,
                'title' => 'Oraimo Watch 5R Pro 1.43" AMOLED 2.5D Floating Interface IP68 Smart Watch',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40221,
                'title' => '100 Non-Stick Air Fryer Sheets With High-Temperature Resistance - Brown',
                'quantity' => 1,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40236,
                'title' => 'Sinotec Smart TV HS-8908J-04 Replacement Remote Control',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40239,
                'title' => 'Phone-Box MagSafe Cover Compatible with Samsung Galaxy S25/ S25 Plus/ S25 Ultra',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40243,
                'title' => '32 Pair Shoe Rack Organizer',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40248,
                'title' => '4 Pack Combo Two Way Walkie Talkie Radio Set',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40250,
                'title' => '14 Piece Whiskey Glasses and Stones Gift Set for Men',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40253,
                'title' => 'magnet - 4K Super Drone Foldable Rechargeable Drone',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40260,
                'title' => 'Adidas Hybrid 25 AeroReady Boxing Gloves - Various Colours and Sizes',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40271,
                'title' => 'GetUp Classic Dartboard with Cabinet Includes 6x18g Steel Darts',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40272,
                'title' => 'Rare Health Herbs Muvevha Enlargement Oil',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40276,
                'title' => 'LEGO® City Passenger Aeroplane 60367 Building Toy Set (930 Pieces)',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40281,
                'title' => 'Decor Chair Protector Mat For Hardwood Floor 120cm',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40286,
                'title' => 'Fertipil Plus PCOS (60 Sachets) x2',
                'quantity' => 1,
                'destination' => 'Zambia',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40288,
                'title' => 'MC Waterproof Backpack #1 - Black',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40288,
                'title' => 'Ashwagandha 60 Capsules',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40300,
                'title' => 'Bennett Read PowerPod Upholstery and Spot Deep Cleaner',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40301,
                'title' => 'PERILLA - Extra Heavy Duty Ironing Board _ Copper Plated_Anthracite PREMIUM',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40304,
                'title' => 'CeraVe Blemish Control Face Cleanser with 2% Salicylic Acid 236ml',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40304,
                'title' => 'Olgani - Copper Curve Tongue Cleaner',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40304,
                'title' => 'CeraVe Advanced Repair Ointment for Very Dry and Chapped Skin 88 ml',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40304,
                'title' => 'PERILLA - Extra Heavy Duty Ironing Board _ Copper Plated_Anthracite PREMIUM',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40324,
                'title' => 'NIVEA Skin Glow Serum-Infused Micellar Cleansing Water, 400ml',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40324,
                'title' => 'BioLife Evening primrose Oil - 1000mg',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40330,
                'title' => 'Nail Art Tools Sterilizer LED Disinfect Machine',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40331,
                'title' => 'Trojan Push Up Bars',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40331,
                'title' => 'SKS Mudguard Set + Stays + Dual-Spoiler Function: Tyres 32mm+ Speedrocker',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40333,
                'title' => 'Radiator Pressure Cap 90KP Compatible With Ford Series',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40335,
                'title' => 'Foldable-Reclining Single Bed Patio Lounge Chair',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40339,
                'title' => 'Awning Warehouse 4.5m x 1m Bronze Tinted',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40348,
                'title' => 'Built-In Circulating Fan Biltong Maker - 861545',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40353,
                'title' => 'LCD TV Remote Control Smart TV Remote Control for Hisense',
                'quantity' => 1,
                'destination' => 'Bulawayo',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6976,
                'received_by' => null,
                'notes' => null,
            ],
            [
                'order' => 40374,
                'title' => 'Mobile Phone Gaming Clamp for PS4 Dual Shock Controller',
                'quantity' => 1,
                'destination' => 'Harare',
                'status' => null,
                'transporter' => null,
                'date' => null,
                'eta' => null,
                'f_status' => null,
                'signed_by' => 6975,
                'received_by' => null,
                'notes' => null,
            ]
        ];

        foreach ($shipments as $shipment) {
            InventoryShipment::create($shipment);
        }

        $this->command->info('✅ Created ' . count($shipments) . ' sample inventory shipments');
    }
}

